# Generated by Django 5.1.6 on 2025-03-05 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.JSONField(default=list)),
                ('keywords', models.JSONField(default=list)),
            ],
        ),
    ]
