# Generated by Django 5.1.6 on 2025-03-05 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_feed_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserKeywordClicks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('keyword_clicks', models.JSONField(default=dict)),
            ],
        ),
        migrations.DeleteModel(
            name='Feed',
        ),
    ]
