# Generated by Django 5.1.6 on 2025-03-06 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_userkeywordclicks_delete_feed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userkeywordclicks',
            name='user_id',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
